# Generated by Django 5.1.2 on 2024-11-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=155)),
                ('rollno', models.IntegerField()),
                ('course', models.TextField(max_length=155)),
            ],
        ),
    ]
