# Generated by Django 5.1.2 on 2024-12-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eight',
            name='name',
            field=models.IntegerField(),
        ),
    ]
